// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // La CLI (migrate/studio) usa la conexión de MIGRACIONES: rol con DDL
    // (DIRECT_URL). El runtime de la app usa DATABASE_URL — rol restringido
    // sin DDL — vía el adapter de src/core/lib/prisma.ts.
    // Ver docs/01-arquitectura.md, sección "Split de roles de DB".
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
